"""empty message

Revision ID: 1d7e8d150a0e
Revises: 0e01aeddbdef
Create Date: 2019-12-22 15:20:35.228151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d7e8d150a0e'
down_revision = '0e01aeddbdef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=False))
    # Manually changed / added to account for existing values in database:
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))

    op.execute('UPDATE todos SET completed = False WHERE completed IS NULL')
    op.alter_column('todos', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
